### ISSUE TITLE
pressing enter in search field

### ISSUE THREAD

**Issue by toooni** [yanickrochon/jquery.uix.multiselect#19]
if something is typed in the search field and enter is pressed before the search results appear, all items will be selected.

**Comment by demonslord** [comment]
Hey, can't confirm this on:
- jquery 1.8.2
- jquery UI 1.8.23
- last version of jquery.multiselect-2

Best Regards,
Alexander Bulei

**Comment by yanickrochon** [comment]
Yeah, it's a weird issue and I wouldn't know what causes this to happen... (everything being selected)

**Comment by toooni** [comment]
This problem happens on the demo page too: http://mind2soft.com/labs/jquery/multiselect/

Pressing enter in the search field does select all found items (moves them from the right to the left box). And if you press enter in the time between entering the search term and the displaying of the search result, all items will be selected.

This happens on Chrome 24.0.1312.57 and Firefox 18.0.2 on OSX.

**Comment by demonslord** [comment]
Hey, its happens because of version jquery (1.9.x)
I don't know why, but on "enter" pressed, its call click event..hmm..very strange.

You can prevent this by follow code:

Line: 83
Replace with: 

.click(function(e) { e.preventDefault(); e.stopPropagation(); if ((/1.9/).test($.fn.jquery) && (e.originalEvent.rangeParent)) {  that.optionCache.setSelectedAll(true); } return false; })

If author want, i can make PR :)

Best Regards.

**Comment by yanickrochon** [comment]
Another fix will have to be found for this issue. Having jQuery version sniffing is as bad as browser feature sniffing. The real cause of this problem can be found without hacking a solution for it. At the moment, it is considered a minor bug that will have to be resolved, however, before the 2.0 (final) milestone deadline.

**Comment by demonslord** [comment]
I will try simulate this issue in jsfiddle.net.
Later, will ask jquery team, because in jquery 1.8.2 it doesn't happens.

Best Regards.
