### ISSUE TITLE
Just Click to select?

### ISSUE THREAD

**Issue by gilbox** [yanickrochon/jquery.uix.multiselect#3]
I want to allow  the user to just click to select an item, without having to drag it. And, if possible, click to deselect as well. Is this possible without modifying the code too much?

**Comment by yanickrochon** [comment]
I just tried a quick fix for your requested feature, unfortunately it is not as simple as it looks. Since there are (can be) animations and the selection is based on elements in the selected/available lists to be placed, if a user would do some fast clicks in a list or another will cause some element states discrepancy (some elements will not appear and/or will lose their draggable settings).

The widget is implemented to render as fast as possible and work out of a single list (sorted once) of elements. If someone can do a PR I'll be glad to review it and merge. Or you can wait until I clear my schedule some more so I can figure out a way to cleanly add a click-to-select behavior on the lists (eventually adding navigation too in some future...)

In any case, thank you for spotting this... issue.

Cheers!

**Comment by gilbox** [comment]
Thanks for the reply. This list is great because scrolling, filtering, and select-all all worked incredibly fast with 5000 items in the list. The animations and drag-n-drop behavior are nice additions but not essential. I'm surprised you added dragging before clicking, but excellent work in any case!

**Comment by yanickrochon** [comment]
Forgot to mention it in the last push, but see the [feature-click-select](https://github.com/yanickrochon/jquery.multiselect-2/tree/feature-click-select) branch.

**Comment by yanickrochon** [comment]
I think I fixed the problem just now! I had to revert some commits as my commit tree was corrupted, but I'm now back in sync with the github repository! And you may check the [feature-click-select](https://github.com/yanickrochon/jquery.multiselect-2/tree/feature-click-select) branch. If it is stable enough, it will be merged with master.

**Comment by yanickrochon** [comment]
This has now been implemented and stable enough.
