### ISSUE TITLE
browser freeze on large pool of elements

### ISSUE THREAD

**Issue by dmill-bz** [yanickrochon/jquery.uix.multiselect#45]
Hello,

I've been testing this out a lot lately. I seem to be getting browser freezes upon loading 1000+ elements. I'm just using the basic .multiselect(), but I've also tried with a natural sort and it's roughly the same. Is there a setting I'm missing that can pace the initialising? 
(these lockups are way shorter than in the previous version, but still present)

Thanks in advance!

**Comment by yanickrochon** [comment]
JavaScript is relatively slow inside a browser, and you will hit bottlenecks in performance. The widget was rewritten to permit greater performance than it's predecessor, but it is still limited by the browser engine. You might get better results with Chrome and IE10, though. In any case, there's not much you can do about it. My tests have shown that a thousand element takes about less than 2 seconds to generate with Chrome (longer with IE9 and earlier).

I have not fully tested this, but you _may_ get a little improvement by using OPTGROUPs; if you segment your options into groups (alphabetically, or otherwise). Putting options in groups does not affect form submission.

**Comment by dmill-bz** [comment]
Fair enough. We've tested a bit more and it seems like some configurations don't experience any lag.  I think it's a fair assessment to say that this will ease out as computers get upgraded. I haven't tried using OPTGROUPs but if I get around to it I'll let you know how it went.
