### ISSUE TITLE
Diacritic insensitive search

### ISSUE THREAD

**Issue by dmill-bz** [yanickrochon/jquery.uix.multiselect#67]
Hello!

I've been wondering if there was any way of accomplishing this? Is there a way of overriding the search function/regex/etc... like we can overwrite sorting?

Essentialy I would like the following to work:
search: mere
find : mêre (or mére etc..)

Thanks in advance for your time.

**Comment by yanickrochon** [comment]
This is the same issue as #15 . It is certainly possible to bring this enhancement to the widget and I shall make it happen as soon as my schedule clear out. I have not set a milestone date for [2.1](https://github.com/yanickrochon/jquery.uix.multiselect/issues?milestone=3&state=open) because of that, but I sure wish to bring the widget around that corner some day!

Anyone who want to venture and implement this, I can provide the specs and guidelines (or can review a PR at best) to do it though.

**Comment by dmill-bz** [comment]
I'm very late in replying, but thanks for the answer!!
