### ISSUE TITLE
this._elements[i] is undefined  on line 767

### ISSUE THREAD

**Issue by jmelnik** [yanickrochon/jquery.uix.multiselect#7]
Found what appears to be a small bug. 

When I do:

```
 $("#multiselect).empty();
 $("#multiselect).multiselect('refresh');
```

I get

```
this._elements[i] is undefined
```

in firebug.

on line 767. If I change it to:

```
if (this._elements[i]) {
    gData[this._elements[i].selected ? 'selected' : 'available'].count++;
}
```

the error goes away and it seems to work fine to empty the select list between ajax calls. Not sure that's the 'correct' way to handle it though.

**Comment by yanickrochon** [comment]
That won't work, and is not clean :) 

Instead, do this (if it works, you can do a PR, or I can push a new commit later on)

Using the current sources, replace line 987 with these :

```
    v.startIndex = -1;  // reset startIndex and counter
    v.count = 0;
}, this._listContainers, this._widget.options.showDefaultGroupHeader);
```

This is in the `_reIndex` function, inside at the end of the `this._groups.each(...)` callback.

The problem seems to be that the groups are not updating correctly, so we force them to do so. I just performed a quick test, and it seems to fix the problem.

**Comment by yanickrochon** [comment]
Never mind that, I have found another issue with it.

I'll post more details of the problem when I resolve it. Meanwhile, if this _does_ solve your problem temporarily, use it. I'll come up with an official fix this week.

**Comment by yanickrochon** [comment]
It seems that the problem comes from the `OptionCache`'s `filter` function where it sets `filtered = true` too aggressively! 

Adding

```
} else if (eData.selected) {
    eData.filtered = false;
}
```

to the filtering condition seems to help it, but I have changed some other things (trying to fix other potential problems like such) and I'd have to push a new commit to make sure it solves this issue for good!

**Comment by jmelnik** [comment]
This appears to be fixed!

Unfortunately, I'm still getting the IE8 'object doesn't support this property or method' on the indexOf line (see issue 8).
